apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "luks-trim.fullname" . }}-script
  namespace: {{ include "luks-trim.namespace" . }}
  labels:
    {{- include "luks-trim.labels" . | nindent 4 }}
data:
  trim.sh: |
{{- tpl (.Files.Get "files/trim.sh") . | nindent 4 }}
